# test_final_state.py
import os
import json
import subprocess
import pytest

NOTEBOOK_PATH = "/home/user/standardize_data.ipynb"
OUTPUT_CSV_PATH = "/home/user/clean_inventory.csv"
OUTPUT_JSON_PATH = "/home/user/schema_report.json"

EXPECTED_CSV_CONTENT = """item_id,product_name,product_price,date_added
101,Widget A,12.5,2022-12-31
102,Widget B,15.0,2023-01-15
103,Widget C,,2023-01-15
104,Widget D,9.99,
105,Widget E,,2023-03-05"""

EXPECTED_SCHEMA = {
    "item_id": "int64",
    "product_name": "object",
    "product_price": "float64",
    "date_added": "object"
}

def test_notebook_exists_and_runs():
    """Verify that the notebook exists and executes without error."""
    assert os.path.isfile(NOTEBOOK_PATH), f"Notebook missing at {NOTEBOOK_PATH}"

    # Remove existing outputs to ensure they are generated by this run
    if os.path.exists(OUTPUT_CSV_PATH):
        os.remove(OUTPUT_CSV_PATH)
    if os.path.exists(OUTPUT_JSON_PATH):
        os.remove(OUTPUT_JSON_PATH)

    result = subprocess.run(
        ["jupyter", "nbconvert", "--execute", "--to", "notebook", "--inplace", NOTEBOOK_PATH],
        capture_output=True,
        text=True
    )

    assert result.returncode == 0, f"Notebook execution failed. Stderr: {result.stderr}"

def test_clean_inventory_csv_exists_and_correct():
    """Verify the cleaned CSV is correctly formatted."""
    assert os.path.isfile(OUTPUT_CSV_PATH), f"Cleaned CSV missing at {OUTPUT_CSV_PATH}"

    with open(OUTPUT_CSV_PATH, "r", encoding="utf-8") as f:
        content = f.read().strip()

    # Replace CRLF with LF to ensure consistent comparison
    content = content.replace("\r\n", "\n")

    lines = content.strip().split("\n")
    header = lines[0]
    assert header == "item_id,product_name,product_price,date_added", f"Wrong header: {header}"
    assert len(lines) == 5, f"Expected 5 lines (header + 4 rows), got {len(lines)}"
    # Check that prices are numeric and names are trimmed
    for line in lines[1:]:
        parts = line.split(",")
        assert len(parts) == 4, f"Wrong number of columns in: {line}"
        assert parts[1].strip() == parts[1], f"Product name not trimmed: '{parts[1]}'"
        try:
            float(parts[2])
        except ValueError:
            assert False, f"Price not numeric: '{parts[2]}'"

def test_schema_report_json_exists_and_correct():
    """Verify the schema report JSON is correctly formatted."""
    assert os.path.isfile(OUTPUT_JSON_PATH), f"Schema JSON missing at {OUTPUT_JSON_PATH}"

    with open(OUTPUT_JSON_PATH, "r", encoding="utf-8") as f:
        try:
            schema = json.load(f)
        except json.JSONDecodeError:
            pytest.fail(f"File {OUTPUT_JSON_PATH} does not contain valid JSON.")

    assert schema == EXPECTED_SCHEMA, f"Content of {OUTPUT_JSON_PATH} does not match expected schema dict. Got {schema}"